"""Internal tool-bridge API for the Codex MCP bridge.

The Codex CLI adapter spawns an MCP bridge script (agenthub-codex-mcp.mjs)
that calls this endpoint to execute AgentHub tools (write_artifact, fs_read,
bash, etc.) on behalf of the codex CLI process.

Authentication: Per-run bearer token generated by ``generate_tool_token`` in
the adapter's ``stream()`` method. The token is scoped to a single run_id
and revoked when the run finishes.

Wire contract (matching agenthub-codex-mcp.mjs):
  Request:  POST /api/internal/agenthub-tools
            Authorization: Bearer <token>
            { toolName, args, conversationId, agentId, runId }
  Response: { ok: true, value: <tool result> }
            { ok: false, error: <message> }
"""

from __future__ import annotations

import asyncio
import logging

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel

from app.services.fs_service import get_workspace_for_conversation
from app.tools.base import ToolContext
from app.tools.internal_token import validate_tool_token
from app.tools.registry import tool_registry
from app.utils.workspace_utils import get_effective_cwd

logger = logging.getLogger(__name__)

router = APIRouter()


class _ToolRequest(BaseModel):
    toolName: str
    args: dict
    conversationId: str
    agentId: str
    runId: str


@router.post("/internal/agenthub-tools")
async def execute_internal_tool(request: Request) -> JSONResponse:
    """Execute an AgentHub tool on behalf of the Codex MCP bridge."""
    # ─── 1. Extract and validate bearer token ───
    auth = request.headers.get("authorization", "")
    if not auth.startswith("Bearer "):
        return JSONResponse(
            {"ok": False, "error": "Missing or invalid Authorization header"},
            status_code=401,
        )
    token = auth[7:]  # strip "Bearer "

    try:
        body = await request.json()
    except Exception:
        return JSONResponse(
            {"ok": False, "error": "Invalid JSON body"},
            status_code=400,
        )

    try:
        req = _ToolRequest(**body)
    except Exception as e:
        return JSONResponse(
            {"ok": False, "error": f"Invalid request body: {e}"},
            status_code=400,
        )

    if not validate_tool_token(req.runId, token):
        logger.warning(
            "[internal-tools] invalid token for run %s (tool=%s)",
            req.runId,
            req.toolName,
        )
        return JSONResponse(
            {"ok": False, "error": "Invalid or expired tool token"},
            status_code=403,
        )

    # ─── 2. Build ToolContext ───
    workspace = await get_workspace_for_conversation(req.conversationId)
    workspace_path = get_effective_cwd(workspace) if workspace else ""

    ctx = ToolContext(
        conversation_id=req.conversationId,
        workspace_path=workspace_path,
        agent_id=req.agentId,
        run_id=req.runId,
        cancel_event=asyncio.Event(),
    )

    # ─── 3. Execute tool ───
    logger.info(
        "[internal-tools] executing tool=%s conv=%s agent=%s run=%s",
        req.toolName,
        req.conversationId,
        req.agentId,
        req.runId,
    )
    result = await tool_registry.execute(req.toolName, req.args, ctx)

    if result.ok:
        return JSONResponse({"ok": True, "value": result.value})
    return JSONResponse(
        {"ok": False, "error": result.error or "Unknown error"},
        status_code=200,  # MCP bridge expects 200 with error body, not HTTP error
    )
